### ISSUE TITLE
The application package name must be whitelisted

### ISSUE THREAD

**Issue by witrisna** [googlecodelabs/fido2-codelab#5] opened 2020-01-16 23:33 UTC
With the sample application, after I click on the FAB registerRequest(), there is no fingerprint dialog and in the logcat console I got below error exception:

`Caused by: java.lang.IllegalArgumentException: This application is not allowed to call FIDO2 API. The application package name must be whitelisted.
        at com.google.android.gms.fido.fido2.ui.AuthenticateChimeraActivity.onCreate(:com.google.android.gms@16089022@16.0.89 (040700-239467275):53)
        at com.google.android.chimera.Activity.publicOnCreate(Unknown Source:0)
        at dvo.onCreate(:com.google.android.gms@16089022@16.0.89 (040700-239467275):6)
        at ppa.onCreate(:com.google.android.gms@16089022@16.0.89 (040700-239467275):2)`

I am testing with Pixel 3 XL API 28 emulator

assetlinks.json
Here is the https://frosted-cod.glitch.me/.well-known/assetlinks.json

The sha256 key is generated by the debug.jks, but I tried ~/.android/debug.keystore also, both have the same error message.

**Comment by witrisna** [comment] 2020-01-17 02:13
Update Google play service 19.8.31

Got another error message:

2020-01-16 18:11:19.736 13544-13544/? E/DeviceDoctorHandler: FATAL EXCEPTION: main
    Process: com.google.android.gms.ui, PID: 13544
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.fido.fido2.ui.Fido2FullScreenActivity}: java.lang.NullPointerException: throw with null exception
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: throw with null exception
        at bned.a(:com.google.android.gms@19831040@19.8.31 (120700-284611645):1)
        at yki.<init>(:com.google.android.gms@19831040@19.8.31 (120700-284611645):1)
        at ycu.<init>(:com.google.android.gms@19831040@19.8.31 (120700-284611645):7)
        at xzp.a(:com.google.android.gms@19831040@19.8.31 (120700-284611645):30)
        at xzp.b(:com.google.android.gms@19831040@19.8.31 (120700-284611645):10)
        at com.google.android.gms.fido.fido2.ui.AuthenticateChimeraActivity.onCreate(:com.google.android.gms@19831040@19.8.31 (120700-284611645):45)
        at com.google.android.chimera.Activity.publicOnCreate(Unknown Source:0)
        at qtf.onCreate(:com.google.android.gms@19831040@19.8.31 (120700-284611645):7)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by witrisna** [comment] 2020-01-17 02:37
I tested on Physical device with Google Play Service 19.8.31 and 20.1.03, both work well, I think the problem may be just on emulator.

**Comment by yaraki** [comment] 2020-01-17 02:53
It seems like an emulator issue. Please make sure that the emulator AVD has a fingerprint sensor configured.

**Comment by witrisna** [comment] 2020-01-17 02:56
Yes, confirmed, I have fingerprint configured.

**Comment by yaraki** [comment] 2020-01-17 04:08
I believe the issue is in Google Play Services. I informed the team of this issue.

**Comment by yaraki** [comment] 2020-01-23 06:59
The issue in Play Services is fixed internally.
It will be released in a while, but for now, please use a device with Bluetooth support.

**Closed by yaraki** 2020-01-23 06:59 UTC

**Comment by samburnstone** [comment] 2021-11-30 17:58
I've just tried out the sample and I still seem to be getting a similar fatal error even when using `com.google.android.gms:play-services-fido:19.0.0-beta`. Is the Emulator still unable to be used currently to test authentication?

I was using the Pixel XL API 29 Emulator with a fingerprint configured. I am able run the sample fine on a hardware device.

The full error message:
```
2021-11-30 17:49:38.737 10207-10207/com.google.android.gms.ui E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gms.ui, PID: 10207
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.fido.fido2.ui.Fido2FullScreenActivity}: java.lang.NullPointerException: throw with null exception
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: throw with null exception
        at bowv.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):1)
        at xzh.<init>(:com.google.android.gms@202414022@20.24.14 (040700-319035315):1)
        at xrn.<init>(:com.google.android.gms@202414022@20.24.14 (040700-319035315):9)
        at xoj.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):30)
        at xoj.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):23)
        at com.google.android.gms.fido.fido2.ui.AuthenticateChimeraActivity.onCreate(:com.google.android.gms@202414022@20.24.14 (040700-319035315):51)
        at com.google.android.chimera.ActivityBase.publicOnCreate(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
        at qlj.onCreate(:com.google.android.gms@202414022@20.24.14 (040700-319035315):6)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by samburnstone** [comment] 2021-12-01 09:51
Just a quick update - I tried creating a new virtual device using API 30, which gave me a different error which said something along the lines of "Google Play Store is missing".

I created another virtual device this time with API 30 and one that [implemented the Google Play Store services](https://stackoverflow.com/a/69047189) and it seems to be working now on the emulator 🎉
